version: "3.5"
services:
  portfolio:
    build: .
    image: "portfolio_${ENVIRONMENT}"
    ports:
      - 5000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_${ENVIRONMENT}.rule=Host(${HOST})"
      - "traefik.http.routers.portfolio_${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.portfolio_${ENVIRONMENT}.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    name: jnet