version: "3.5"
services:
  portfolio:
    build:
      context: .
    ports:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER}.rule=Host(${HOST})"
      - "traefik.http.routers.${ROUTER}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER}.tls.certresolver=letsencrypt"
    networks:
      - jnet
networks:
  jnet:
    external:
      name: jnet
