pipeline {
  agent any
  tools {
    nodejs "node16"
  }
  environment {
    GH_TOKEN = credentials("gh-pat")
  }
  stages {
    stage("Skip Gate") {
      when {
        not {
          //Skip pipeline if last commit was generated by CI already.
          changelog '.*\\[skip ci\\].*' 
        }
      }
      stages {
        stage("Install") {
          steps {
            sh "npm ci"
          }
        }
        stage("Lint") {
          steps {
            sh "npm run lint"
          }
        }
        stage("Versioning") {
          when { branch 'master' }
          steps {
            sh "npx semantic-release"
          }
        }
        stage("Prepare Deployment") {
          parallel {
            stage("Production") {
              when { branch 'master' }
              steps {
                withCredentials([file(credentialsId: 'env-production-portfolio', variable: 'ENV_FILE')]) {
                  writeFile file: '.env', text: readFile(ENV_FILE)
                }
              }
            }
            stage("Staging") {
              when { not { branch 'master' } }
              steps {
                withCredentials([file(credentialsId: 'env-staging-portfolio', variable: 'ENV_FILE')]) {
                  writeFile file: '.env', text: readFile(ENV_FILE)
                }
              }
            }
          }
        }
        stage("Deploy") {
          when { expression { env.CHANGE_ID == null } }
          steps {
            script {
              withCredentials([usernamePassword(credentialsId: 'jenkinsUser', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                def remote = [:]
                remote.name = "vserver"
                remote.user = "$USERNAME"
                remote.host = "feuer.dev"
                remote.password = "$PASSWORD"
                remote.allowAnyHosts = true
                sshCommand remote: remote, command: "git clone -b ${env.BRANCH_NAME} --single-branch ${GIT_URL} ${env.BRANCH_NAME}"
                sshPut remote: remote, from: ".env", into: "${env.BRANCH_NAME}"
                sshCommand remote: remote, command: "cd ${env.BRANCH_NAME}; sudo docker-compose down; sudo docker-compose up -d --build"
                sshRemove remote: remote, path: "${env.BRANCH_NAME}"
              }
            }
          }
        }
      }
    }
  }
}